services:
  - type: web
    name: server
    runtime: node
    rootDir: .
    startCommand: npm install && npm run prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
